---

- name: Tareas de despliegue automático en arch linux
  hosts: archible.casa.lan
  vars_prompt:
    - name: users_user_name
      prompt: ¿Nombre de usuario para crear?
      private: false
      default: oloco

  vars:
    PYTHONDONTWRITEBYTECODE: False
    # Es mejor usar un .gitignore con "**/__pycache__/"

  become: true
  roles:
#    - role: "pre_tasks"
    - role: sysupgrade # Actualiza paquetes y luego sistema
#      tags: ["update_packages", "upgrade_system"]
    - role: packages # Instala la paquetería
#    - role: "grub" # Actualiza el valor de GRUB_TIMEOUT en /etc/default/grub.
      tags: ["grub"]
    - role: groups
#      tags: [""]
    - role: users
#      tags: [""]
    - role: sudo
#      tags: [""]
#    - role: zsh 
#      tags: ["zsh"]
    - role: openssh
#      tags: ["penssh"]



#  tasks:
#    - name: Incluir mi tarea personalizada
#      ansible.builtin.include_tasks: tests.yml

...
