#- block: 

- name: do a thing
  ansible.builtin.uri:
    url: https://derpops.bike
  register: derpops
- name: show derpops
  ansible.builtin.debug:
    msg: "derpops value is {{ derpops }}"



- name: subscript style
  ansible.builtin.debug:
    var: derpops['connection']

- name: dot notation style
  ansible.builtin.debug:
    var: derpops.url
