---
# defaults file for groups

# Mete al usuario al grupo de sudoers adecuado en función de la distribución detectada
groups_sudo_group: "{{ 
  'sudoers' if ansible_distribution == 'Ubuntu' else 
  'sudo' if ansible_distribution == 'Debian' else 
  'wheel' if ansible_distribution in ['CentOS', 'RedHat', 'Archlinux'] else 
  'wheel'
}}"

...
