---

- name: Obtener lista de archivos en la ruta /tmp/ansible/etc_files/zsh/
  ansible.builtin.find:
    paths: /tmp/ansible/etc_files/zsh/
  register: archivos_encontrados

- name: Copiar archivos encontrados al directorio /etc/zsh en el servidor remoto
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "/etc/zsh/{{ item.path | basename }}"
    backup: yes
    force: yes
    mode: "0644"
    directory_mode: "0755"
    remote_src: yes
    group: root
    owner: root
  with_items: "{{ archivos_encontrados.files }}"


- name: Seteamos ZSH como terminal por defecto a nuevos usuarios
  ansible.builtin.lineinfile:
    path: "{{ zsh_default_shell_useradd_file }}"
    line: "SHELL=/usr/bin/zsh"
    regexp: "^SHELL="
    backup: yes
    state: present


- name: Obtener la shell del usuario "root"
  ansible.builtin.user:
    name: "root"
  register: user_info


- name: Cambiar shell de root
  ansible.builtin.user:
    name: "root"
    shell: "/bin/{{ zsh_root_shell }}"
  when: not user_info.shell | regex_search('.*zsh$')
