---

- name: "Copiar archivos de {{ zsh_src_dir }} al directorio {{ zsh_dest_dir }} en el servidor remoto"
  ansible.builtin.copy:
    src: "{{ zsh_src_dir }}"
    dest: "{{ zsh_dest_dir }}"
    backup: yes
    force: yes
    directory_mode: "0755"
    mode: "0755"
    remote_src: yes
    group: root
    owner: root


- name: Seteamos ZSH como terminal por defecto a nuevos usuarios
  ansible.builtin.lineinfile:
    path: "{{ zsh_default_shell_useradd_file }}"
    line: "SHELL=/usr/bin/zsh"
    regexp: "^SHELL="
    backup: yes
    state: present


- name: Obtener la shell del usuario "root"
  ansible.builtin.user:
    name: "root"
  register: user_info


- name: Cambiar shell de root
  ansible.builtin.user:
    name: "root"
    shell: "/bin/{{ zsh_root_shell }}"
  when: not user_info.shell | regex_search('.*zsh$')
