---
# tasks file for git
- name: "Creamos directorio de destino {{ git_dest_folder }} "
  ansible.builtin.file:
    follow: true
    group: "{{ users_user_name }}"
    mode: "0755"
    owner: "{{ users_user_name }}"
    path: "{{ git_dest_folder }}"
    recurse: false
    state: directory
    unsafe_writes: false

- name: "Creamos fichero de config de git en {{ git_conf_file_dest_path }}"
  ansible.builtin.template:
    src: git_config.j2
    dest: "{{ git_conf_file_dest_path }}"
    owner: "{{ users_user_name }}"
    group: "{{ users_user_name }}"
    mode: "0644"

- name: "Crear ficheros de credenciales de git en {{ git_cred_file_dest_path }}"
  ansible.builtin.copy:
    content: "{{ git_token }}"
    dest: "{{ git_cred_file_dest_path }}"
    owner: "{{ users_user_name }}"
    group: "{{ users_user_name }}"
    mode: "0600"
  no_log: true
