---
# tasks file for users

- name: Llamamos al detector de distros en caso de no existir la variable groups_sudo_group
  ansible.builtin.include_tasks: roles/groups/tasks/groups_sudo.yml
  when: not groups_sudo_group is defined

- name: "Crear usuario {{ users_user_name }} y meterlo al grupo {{ groups_sudo_group }}"
  ansible.builtin.user:
    state: present
    name: "{{ users_user_name }}"
    generate_ssh_key: true
    ssh_key_bits: 2048
    ssh_key_file: ".ssh/id_rsa"
    ssh_key_type: rsa
    create_home: true
    comment: "Usuario {{ users_user_name }}"
    append: true
    groups: "{{ groups_sudo_group }}"
    shell: /bin/zsh
    password: "{{ users_user_passwd | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"
    # update_password: on_create
    # Para evitar que ansible detecte un cambio de contraseña a pesar de ser la misma, podemos usar el mismo salt
    # password: "{{ generic_password | password_hash('sha512', 'mysalt') }}"


- name: "Crear usuario ansible"
  ansible.builtin.user:
    state: present
    name: "ansible"
    generate_ssh_key: true
    ssh_key_bits: 2048
    ssh_key_file: ".ssh/id_rsa"
    ssh_key_type: rsa
    create_home: true
    comment: "Usuario Ansible"
    shell: /bin/zsh
    password: "{{ passwords.ansible }}"


...
