---
# tasks file for users


- name: "Crear usuario {{ users_user_name }} y meterlo al grupo {{ groups_sudo_group }}"
  ansible.builtin.user:
    state: present
    name: "{{ users_user_name }}"
    create_home: true
    comment: "Usuario {{ users_user_name }}"
    append: true
    groups: "{{ groups_sudo_group }}"
    shell: /bin/zsh




# Revisar si realmente hace falta
- name: Crear el usuario ansible
  ansible.builtin.user:
    state: present
    name: ansible
    create_home: true
    comment: ansible
    shell: /bin/zsh


...
