---
# tasks file for users

- name: Llamamos al detector de distros
  ansible.builtin.include_tasks: roles/groups/tasks/groups_sudo.yml


- name: "Comprobar si el grupo {{ groups_sudo_group }} ya existe"
  ansible.builtin.group:
    name: "{{ groups_sudo_group }}"
  register: grupo_sudo

- name: "Crear el grupo {{ groups_sudo_group }} si no existe"
  ansible.builtin.group:
    name: "{{ groups_sudo_group }}"
    state: present
  when: grupo_sudo.state == "absent"

